name: Report Exploit
description: Report an exploit to be added to the repository
labels: ["submission", "exploit"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the exploit
      placeholder: Example Exploit
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the exploit
      placeholder: This exploit takes advantage of...
    validations:
      required: true

  - type: textarea
    id: addresses
    attributes:
      label: Addresses
      description: 'A list of affected addresses, with the chainId and address for each (one per line, in the format "chainId: address")'
      placeholder: "1: 0x1234...ABCD"
    validations:
      required: true

  - type: textarea
    id: metaArticleUrls
    attributes:
      label: Meta Article URLs
      description: A list of URLs to articles or resources with more information about the exploit (one per line)
      placeholder: "https://example.com/article"
    validations:
      required: true
