name: Report Exploit
description: Report an exploit to be added to the repository
labels: ["submission", "exploit"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an exploit to the repository! Please fill out the following information to the best of your ability. Keep in mind that this repository is specifically for smart contract or frontend exploits that put approved funds at risk. This does not include phishing websites or similar scams.
  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the exploit
      placeholder: Example Exploit
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the exploit
      placeholder: This exploit takes advantage of...
    validations:
      required: true

  - type: textarea
    id: addresses
    attributes:
      label: Addresses
      description: 'A list of affected addresses, with the chainId and address for each (one per line, in the format "chainId: address")'
      placeholder: "1: 0x1234...ABCD"
    validations:
      required: true

  - type: textarea
    id: metaArticleUrls
    attributes:
      label: Meta Article URLs
      description: A list of URLs to articles or resources with more information about the exploit (one per line)
      placeholder: "https://example.com/article"
    validations:
      required: true
